// var email = 'jeery1997@126.com';
// var address =email.indexOf('@');
// var uName = email.slice(0,address);
// var webAdd = email.substr(address+1);
// console.log('用户名是'+uName);
// console.log('域名是'+webAdd);
var word = 'weLCome';
// var lower = word.toLowerCase();
// console.log(lower);
// var fw = lower.substr(0,1);
// var fUp = fw.toUpperCase();
// console.log(fUp);
// var elseW = lower.slice(1);
// var newW = fUp+elseW;
// console.log(newW);
var fUPper = word.substr(0,1).toUpperCase();
var fLower = word.slice(1).toLowerCase();
var newW = fUPper+fLower;
console.log(newW);